[2022-01-07 19:03:55,235] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: zalando_workflow.extract_data scheduled__2021-11-04T00:00:00+00:00 [queued]>
[2022-01-07 19:03:55,243] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: zalando_workflow.extract_data scheduled__2021-11-04T00:00:00+00:00 [queued]>
[2022-01-07 19:03:55,243] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 19:03:55,243] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-07 19:03:55,243] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 19:03:55,391] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): extract_data> on 2021-11-04 00:00:00+00:00
[2022-01-07 19:03:55,394] {standard_task_runner.py:52} INFO - Started process 14441 to run task
[2022-01-07 19:03:55,399] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'zalando_workflow', 'extract_data', 'scheduled__2021-11-04T00:00:00+00:00', '--job-id', '147', '--raw', '--subdir', '/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/dags/zalando_etl.py', '--cfg-path', '/tmp/tmp12twvw7p', '--error-file', '/tmp/tmpj8zbnx5o']
[2022-01-07 19:03:55,401] {standard_task_runner.py:77} INFO - Job 147: Subtask extract_data
[2022-01-07 19:03:55,594] {logging_mixin.py:109} INFO - Running <TaskInstance: zalando_workflow.extract_data scheduled__2021-11-04T00:00:00+00:00 [running]> on host rhavel-VPCEG13EB
[2022-01-07 19:03:55,967] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=zalando_workflow
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-04T00:00:00+00:00
[2022-01-07 19:03:56,290] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/dags/zalando_etl.py", line 16, in extract_data
    json_data = json.loads(res.content)['articles']
  File "/home/rhavel/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/rhavel/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/rhavel/miniconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-01-07 19:03:56,300] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=zalando_workflow, task_id=extract_data, execution_date=20211104T000000, start_date=20220107T220355, end_date=20220107T220356
[2022-01-07 19:03:56,412] {standard_task_runner.py:89} ERROR - Failed to execute job 147 for task extract_data
Traceback (most recent call last):
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/dags/zalando_etl.py", line 16, in extract_data
    json_data = json.loads(res.content)['articles']
  File "/home/rhavel/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/rhavel/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/rhavel/miniconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-01-07 19:03:56,454] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-07 19:03:56,600] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
