[2022-01-07 19:59:14 -0300] [18409] [INFO] Starting gunicorn 20.1.0
[2022-01-07 19:59:14 -0300] [18409] [INFO] Listening at: http://0.0.0.0:8793 (18409)
[2022-01-07 19:59:14 -0300] [18409] [INFO] Using worker: sync
[2022-01-07 19:59:14 -0300] [18410] [INFO] Booting worker with pid: 18410
[2022-01-07 19:59:14 -0300] [18411] [INFO] Booting worker with pid: 18411
Process ForkProcess-2:
Traceback (most recent call last):
  File "/home/rhavel/miniconda3/lib/python3.9/pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'logs/dag_processor_manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rhavel/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rhavel/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/dag_processing/manager.py", line 273, in _run_processor_manager
    importlib.reload(import_module(airflow.settings.LOGGING_CLASS_PATH.rsplit('.', 1)[0]))  # type: ignore
  File "/home/rhavel/miniconda3/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/config_templates/airflow_local_settings.py", line 164, in <module>
    Path(directory).mkdir(parents=True, exist_ok=True, mode=0o755)
  File "/home/rhavel/miniconda3/lib/python3.9/pathlib.py", line 1317, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/rhavel/miniconda3/lib/python3.9/pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: 'logs'
Traceback (most recent call last):
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/bin/airflow", line 8, in <module>
[2022-01-07 19:59:14 -0300] [18409] [INFO] Handling signal: term
    sys.exit(main())
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-07 19:59:14 -0300] [18411] [INFO] Worker exiting (pid: 18411)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/scheduler_command.py", line 70, in scheduler
    _run_scheduler_job(args=args)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/scheduler_command.py", line 46, in _run_scheduler_job
    job.run()
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/jobs/base_job.py", line 245, in run
    self._execute()
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 628, in _execute
    self._run_scheduler_loop()
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 706, in _run_scheduler_loop
    self.processor_agent.wait_until_finished()
[2022-01-07 19:59:14 -0300] [18410] [INFO] Worker exiting (pid: 18410)
  File "/home/rhavel/Documentos/STUDY-PROJECTS/airflow-study/projects/shritam-airflow/venv/lib/python3.9/site-packages/airflow/dag_processing/manager.py", line 229, in wait_until_finished
    result = self._parent_signal_conn.recv()
  File "/home/rhavel/miniconda3/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/rhavel/miniconda3/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/rhavel/miniconda3/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-01-07 19:59:14 -0300] [18409] [INFO] Shutting down: Master
